### ISSUE TITLE
Repository no longer maintained?

### ISSUE THREAD

**Issue by ghost** [cloudbase/unattended-setup-scripts#24]
Pull-requests and issues have not had any attention since at least September 2016. It seems this repostitory is no longer maintained.

@alexpilotti can you confirm or clarify this by any chance?

**Comment by alexpilotti** [comment]
Hi, as per description this is a dump of random scripts that don’t fit somewhere else, not a project, so it’s not really “maintained” in a traditional sense :-)

**Comment by ghost** [comment]
Ok, thanks for answering that :)
